version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: .docker/api/dev/Dockerfile
    hostname: api
    env_file:
      - .env
    ports:
      - '8000:8000'
    tty: true
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./atumm:/home/atumm
      - ./thisapp:/home/thisapp
    logging:
      driver: "json-file"
      options:
        max-size: "60m"
        max-file: "3"
  mongo:
    image: mongo:5.0.16-focal
    hostname: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27888:27017"
    volumes:
      - ./.data/mongo:/data/db
      - ./.docker/mongo/ep.sh:/docker-entrypoint-initdb.d/ep.sh:ro

